theme: jekyll-theme-cayman
title: Huanqiu的博客
author: Huanqiu
description: 感谢有你。
keywords: "blog"
baseurl: 
permalink: /:year/:month/:day/:title/
url: huanqiugame.github.io
version: 0.1.1

relative_links:
    enabled:     true
    collections: true
titles_from_headings:
    enabled:     true
    strip_title: false
    collections: false
